version: 2
updates:
  # Keep GitHub Actions (your workflow .yml files) up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "ci"
    commit-message:
      prefix: "chore(actions)"
    open-pull-requests-limit: 5

  # Optionally, keep your pip dependencies fresh too
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "chore(deps)"

