repos:
  - repo: https://github.com/psf/black
    rev: 23.9.1 # pick a stable release
    hooks:
      - id: black
        language_version: python3


  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0 # pick a stable release
    hooks:
      - id: ruff
        args: [--fix] # auto-fix simple issues
