services:
  api:
    build: .
    container_name: sdsrc-api
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    environment:
      - PYTHONPATH=/app/src
    command: uvicorn sdsrc.api:app --host 0.0.0.0 --port 8000 --reload
