name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]   # install package in edit mode
          pip install pytest # test framework

      - name: Check formatting with black
        run: |
          pip install black
          black --check src tests
      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff check src tests
      - name: Run tests
        run: |
          pytest -q
